globalThis._importMeta_={url:import.meta.url,env:process.env};import 'node:http';
import 'node:https';
export { D as default } from './chunks/nitro/node-server.mjs';
import 'fs';
import 'path';
import 'packrup';
import 'nitropack/dist/runtime/plugin';
import 'vue';
import 'node:fs';
import 'node:url';
import 'ipx';
